version: '3'
services:
  ansible:
    container_name: ansible
    image: ansible
    hostname: ansible
    tty: true
    stdin_open: true
    build:
      context: ./
    volumes:
      - ./inventory/:/inventory/
      - ./ansible.cfg:/ansible.cfg
    networks:
      - net

  remote_host_one:
    container_name: remote-host-one
    image: remote-host-ssh
    hostname: node1
    env_file:
      - .env
    build:
      context: ./sshd-enabled-debian
    networks:
      - net

  remote_host_two:
    container_name: remote-host-two
    image: remote-host-ssh
    hostname: node2
    env_file:
      - .env
    build:
      context: ./sshd-enabled-debian
    networks:
      - net

networks:
  net:
